[tools]
bat = "latest"
btop = "latest"
difftastic = "latest"
dust = "latest"
eza = { version = "latest", postinstall = "fetch-completions-github eza eza-community/eza \"$(basename \"$MISE_TOOL_INSTALL_PATH\")\" \"completions-$(basename \"$MISE_TOOL_INSTALL_PATH\").tar.gz\" \"*/_eza\"" }
fd = "latest"
fzf = "latest"
hexyl = "latest"
jless = "latest"
jq = "latest"
neovim = "latest"
numbat = "latest"
ripgrep = "latest"
sd = "latest"
shellcheck = "latest"
"cargo:tokei" = "latest"
tree-sitter = "latest"
usage = "latest"
uv = "latest"
